sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
  - php: hhvm

env:
  - DB=mysql

before_script:
  - git clone git://github.com/YOURLS/YOURLS-unit-tests.git tests
  - git clone git://github.com/ozh/YOURLS-fr_FR.git user/languages/fr
  - cp user/languages/fr/fr_FR.* user/languages
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp tests/yourls-tests-config-travis.php user/config.php
  - |
    case "$TRAVIS_PHP_VERSION" in
      7.1|7.0|hhvm)
        echo "Using PHPUnit 5.7"
        composer global require "phpunit/phpunit=5.7.*"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.8"
        composer global require "phpunit/phpunit=4.8.*"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac
  - phpunit --version

script: phpunit --configuration ./tests/phpunit-travis.xml.dist

after_script: rm user/config.php

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#YOURLS"
    use_notice: true
